Repository lusitania-labs/aigenda, pull requests merged in 2023-05, with the labels that each got.

#9 Adding changelog, issues and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/change_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: documentation

#10 finishing initial setup
  .gitignore
  CONTRIBUTING.md
  README.md
  core/src/main/kotlin/com/lusitania/labs/aigenda/core/config/OpenApiConfig.kt
  core/src/main/kotlin/com/lusitania/labs/aigenda/core/controller/TodosController.kt
  core/src/main/kotlin/com/lusitania/labs/aigenda/core/dto/GreetingRequestDto.kt
  core/src/main/resources/application.yaml
  core/src/main/resources/static/logo.png
  docs/DEVELOPER_GUIDE.md
  docs/SETUP.md
  docs/images/enable_plugins.png
  docs/images/find_manifest.png
  docs/images/install_plugin.png
  docs/images/logo.png
  docs/images/plugins_store.png
  github/gradle/wrapper/gradle-wrapper.properties
  outlook/build.gradle.kts
  outlook/gradle/wrapper/gradle-wrapper.properties
  outlook/gradlew
  outlook/gradlew.bat
  outlook/settings.gradle.kts
  outlook/src/main/kotlin/com/lusitania/labs/aigenda/outlook/controller/OutlookController.kt
  outlook/src/main/resources/application.yaml
Labels: documentation, enhancement

#11 FEATURE
  .github/core-code-coverage.yml
  .github/gradle-dependency-submission.yml
  README.md
  build.gradle.kts
  core/gradlew
  core/gradlew.bat
  github/gradle/wrapper/gradle-wrapper.properties
  github/gradlew
  github/gradlew.bat
  jira/gradle/wrapper/gradle-wrapper.properties
  jira/gradlew
  jira/gradlew.bat
  outlook/gradle/wrapper/gradle-wrapper.properties
  outlook/gradlew
  outlook/gradlew.bat
Labels: enhancement
